# Site settings
title: >
  Come on, time to robot!
author: Josh Hill
description: >
  I'm an aspiring software craftsman in London who enjoys making things with
  Ruby and encouraging others to learn.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jamesjoshuahill.github.io" # the base hostname & protocol for your site
twitter_username: jamesjoshuahill
github_username: jamesjoshuahill
permalink: pretty
exclude: [vendor]

# Build settings
markdown: kramdown
