# Site settings
title: >
  Time to robot!
author: Josh Hill
description: >
  I'm an aspiring software craftsman in London who enjoys making things with
  code and encouraging others to learn.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jamesjoshuahill.github.io" # the base hostname & protocol for your site
twitter_username: jamesjoshuahill
github_username: jamesjoshuahill
permalink: pretty

# GitHub Pages settings
lsi: false
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
