# Site settings
title: >
  Time to robot!
author: Josh Hill
description: >
  I enjoy learning together, delighting customers and being sincerely silly.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jamesjoshuahill.github.io" # the base hostname & protocol for your site
twitter_username: jamesjoshuahill
github_username: jamesjoshuahill
permalink: pretty

# GitHub Pages settings
lsi: false
plugins:
  - jekyll-sitemap

# Build settings
markdown: kramdown
